# Generated by Django 4.1.7 on 2023-05-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_alter_googleuserinfo_author_alter_qquserinfo_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthuser',
            name='picture',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='token',
            field=models.CharField(max_length=150),
        ),
    ]
