# Generated by Django 4.1.5 on 2023-02-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='creat_time',
            new_name='created_time',
        ),
    ]
