# Generated by Django 4.1.5 on 2023-03-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='wordpress_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='wordpress_category_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='wordpress_tag_id',
        ),
    ]
