# Generated by Django 4.1.5 on 2023-02-28 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('a', '文章'), ('p', '页面')], default='a', max_length=1, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='wordpress_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='category',
            name='wordpress_category_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='tag',
            name='wordpress_tag_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('pub_time', models.DateTimeField(blank=True, help_text='不指定发布时间则为草稿，可以指定未来时间，到时将自动发布。', null=True, verbose_name='发布时间')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '发表')], default='d', max_length=1, verbose_name='文章状态')),
                ('comment_status', models.CharField(choices=[('o', '打开'), ('c', '关闭')], max_length=1, verbose_name='评论状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '页面',
                'verbose_name_plural': '页面',
                'ordering': ['-pub_time'],
            },
        ),
    ]
